export const GET_SNEAKERS = 'GET_SNEAKERS'
export const GET_SNEAKERS_SUCCESS = 'GET_SNEAKERS_SUCCESS'
export const GET_SNEAKERS_API_ERROR = 'GET_SNEAKERS_API_ERROR'


export const GET_A_SNEAKER = 'GET_A_SNEAKER'
export const GET_A_SNEAKER_SUCCESS = 'GET_A_SNEAKER_SUCCESS'
export const GET_A_SNEAKER_API_ERROR = 'GET_A_SNEAKER_API_ERRORÍ'
